name: Publish Container Image
# Build on all changes, such that 'latest' is a development-style release
on:
  push:
    branches: [ main ]
jobs:
  push_to_registry:
    name: Build and Push Container
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Get the Tag Version
        id: get_version
        run: echo ${{ github.ref_name }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log In to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GIT_TOKEN }}
      - name: Push to Container Registries
        uses: docker/build-push-action@v4
        with:
          platforms: |
            linux/386
            linux/amd64
            linux/arm/v6
            linux/arm/v7
            linux/arm64/v8
          push: true
          tags: |
            ${{secrets.DOCKER_USERNAME}}/prometheus-arcadyan-exporter:latest
            ${{secrets.DOCKER_USERNAME}}/prometheus-arcadyan-exporter:${{github.ref_name}}
            ghcr.io/${{github.repository_owner}}/prometheus-arcadyan-exporter:latest
            ghcr.io/${{github.repository_owner}}/prometheus-arcadyan-exporter:${{github.ref_name}}
